# Where things are
source:          .
destination:     _site
#collections_dir: ontology
#plugins_dir:     _plugins
layouts_dir:     ./assets/_layouts
data_dir:        ./assets/_data
includes_dir:    ./assets/_includes

# Handling Reading
safe:                true
include:             [".data"]
exclude:             ["domain", "_site", "*.sh", "*.pst", "~*"]
keep_files:          [".git", ".data", ".config"]
encoding:            "utf-8"
markdown_ext:        "md"
strict_front_matter: true

# Filtering Content
show_drafts: false
limit_posts: 0
future:      true
unpublished: false

# Plugins
#whitelist: []
#plugins:   []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false
verbose:  false

liquid:
  error_mode:       warn
  strict_filters:   false
  strict_variables: false

kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: true

sass:
  sass_dir: ./assets/_sass
  style: compressed
###########################################################################
###                      Generated via gen.sh                           ###
###########################################################################
collections:
  posts:
    output: true
  service:
    output: true
  process:
    output: true
  module:
    output: true
  product:
    output: true
  user:
    output: true
  group:
    output: true
  role:
    output: true
  report:
    output: true
  worksheet:
    output: true
  audio:
    output: true
  image:
    output: true
  documents:
    output: true
  procedure:
    output: true

defaults:
  - scope:
      path: "" # an empty string here means all files in project.
    values:
      layout: "default"
# Process
  - scope:
      path: ""
      type: "process"
    values:
      layout: "process"
      label: process
# Concept
  - scope:
      path: "concept/"
    values:
      layout: "concept"
# Service
  - scope:
      path: "service"
      type: "service"
    values:
      layout: "service"
  - scope:
      path: "user"
    values:
      layout: "user"
  - scope:
      path: "group"
    values:
      layout: "group"
  - scope:
      path: "role"
    values:
      layout: "role"
  - scope:
      path: "product"
    values:
      layout: "product"
  - scope:
      path: "module"
    values:
      layout: "module"
