# Where things are
source:          .
destination:     ./_site
collections_dir: ./ontology
#plugins_dir:     _plugins
layouts_dir:     _layouts
data_dir:        ./_data
includes_dir:    _includes

collections:
  service:
    output: true
  process:
    output: true
  module:
    output: true
  product:
    output: true
  user:
    output: true
  group:
    output: true
  role:
    output: true
  report:
    output: true
  worksheet:
    output: true
  audio:
    output: true
  image:
    output: true
  documents:
    output: true

# Handling Reading
safe:                true
include:             [".data"]
exclude:             ["domain", "_site", "*.sh"]
keep_files:          [".git", ".data", ".config"]
encoding:            "utf-8"
markdown_ext:        "md"
strict_front_matter: true

# Filtering Content
show_drafts: false
limit_posts: 0
future:      true
unpublished: false

# Plugins
#whitelist: []
#plugins:   []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false
verbose:  false

liquid:
  error_mode:       warn
  strict_filters:   false
  strict_variables: false

kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: false

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: "" # an empty string here means all files in project.
    values:
      layout: "default"
  - scope:
      path: "process"
    values:
      layout: "process"
      catagory: "process"
